// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqraz01F_OFFxyr26tayob7NnpSvE2OY',
    appId: '1:27902403594:web:effa3d8e1e453b7f09ebf3',
    messagingSenderId: '27902403594',
    projectId: 'technication-assistant-app',
    authDomain: 'technication-assistant-app.firebaseapp.com',
    storageBucket: 'technication-assistant-app.firebasestorage.app',
    measurementId: 'G-7DWJ3G40D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21eL4DZY7WKsOjde7D5Nc38XDSureuLo',
    appId: '1:27902403594:android:f21858b44411766109ebf3',
    messagingSenderId: '27902403594',
    projectId: 'technication-assistant-app',
    storageBucket: 'technication-assistant-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3sl21DHlI3VWOtt_5zQGImeQaCwiiZ4',
    appId: '1:27902403594:ios:d152f181a444817409ebf3',
    messagingSenderId: '27902403594',
    projectId: 'technication-assistant-app',
    storageBucket: 'technication-assistant-app.firebasestorage.app',
    iosBundleId: 'com.example.technicianAssistantApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm3sl21DHlI3VWOtt_5zQGImeQaCwiiZ4',
    appId: '1:27902403594:ios:d152f181a444817409ebf3',
    messagingSenderId: '27902403594',
    projectId: 'technication-assistant-app',
    storageBucket: 'technication-assistant-app.firebasestorage.app',
    iosBundleId: 'com.example.technicianAssistantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXqraz01F_OFFxyr26tayob7NnpSvE2OY',
    appId: '1:27902403594:web:3c72b4466043800709ebf3',
    messagingSenderId: '27902403594',
    projectId: 'technication-assistant-app',
    authDomain: 'technication-assistant-app.firebaseapp.com',
    storageBucket: 'technication-assistant-app.firebasestorage.app',
    measurementId: 'G-ZJJ8EE91HY',
  );
}
